version: '3.8'

services:
  dooc-nginx:
    image: nginx:1.18.0-alpine
    volumes:
      - "./src/frontend/config/default.conf:/etc/nginx/conf.d/default.conf:rw"
      - "./src/frontend:/usr/share/nginx/html/:rw"
    ports:
      - "8080:80"
    networks:
      - nginx_web
    restart: always
    container_name: UnifiedHealthSystemApplicationNginx

  dooc-mysql:
    image: mysql:8.0.22
    environment:
      MYSQL_ROOT_PASSWORD: "Oy9tiopah0booG5Ooyoh"
    volumes:
      - "./DOOC.sql:/docker-entrypoint-initdb.d/DOOC.sql:ro"
    networks:
      - mysql
    ports:
      - "127.0.0.1:3306:3306"
    command: mysqld --sql_mode="NO_ZERO_DATE" --character-set-server=utf8mb4 --collation-server=utf8mb4_general_ci
    restart: always
    container_name: UnifiedHealthSystemApplicationMySQL

  dooc-java:
    build: .
    image: openjdk:16-alpine3.13
    environment:
      MYSQL_DATASOURCE_URL: "jdbc:mysql://UnifiedHealthSystemApplicationMySQL:3306/DOOC"
      MYSQL_DATASOURCE_USERNAME: "root"
      MYSQL_DATASOURCE_PASSWORD: "Oy9tiopah0booG5Ooyoh"
    container_name: UnifiedHealthSystemApplication
    networks:
      - mysql
      - nginx_web
    restart: always

networks:
  nginx_web:
    external: false
  mysql:
    external: false
